"""Initial migration

Revision ID: eeb902be9f4d
Revises: 
Create Date: 2024-09-12 03:13:52.725009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeb902be9f4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('essay1_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('essay2_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('essay3_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('essay1_feedback', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('essay2_feedback', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('essay3_feedback', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicant', schema=None) as batch_op:
        batch_op.drop_column('essay3_feedback')
        batch_op.drop_column('essay2_feedback')
        batch_op.drop_column('essay1_feedback')
        batch_op.drop_column('essay3_score')
        batch_op.drop_column('essay2_score')
        batch_op.drop_column('essay1_score')

    # ### end Alembic commands ###
